# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: satellite.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsatellite.proto\"\xbb\x01\n\x10SatelliteRequest\x12\x0e\n\x06sat_id\x18\x01 \x02(\x05\x12/\n\x08req_type\x18\x02 \x02(\x0e\x32\x1d.SatelliteRequest.RequestType\x12\x14\n\x0cthrust_angle\x18\x03 \x01(\x01\x12\x13\n\x0bthrust_dura\x18\x04 \x01(\x01\";\n\x0bRequestType\x12\x10\n\x0cLOCATION_REQ\x10\x00\x12\x0c\n\x08TIME_REQ\x10\x01\x12\x0c\n\x08MOVE_REQ\x10\x02\"\xed\x02\n\x11SatelliteResponse\x12\x36\n\tloca_resp\x18\x01 \x01(\x0b\x32#.SatelliteResponse.LocationResponse\x12\x32\n\ttime_resp\x18\x02 \x01(\x0b\x32\x1f.SatelliteResponse.TimeResponse\x12\x32\n\tmove_resp\x18\x03 \x01(\x0b\x32\x1f.SatelliteResponse.MoveResponse\x1a\x37\n\x10LocationResponse\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x1a!\n\x0cTimeResponse\x12\x11\n\tcurr_time\x18\x01 \x01(\x03\x1a\\\n\x0cMoveResponse\x12\x11\n\tresp_code\x18\x01 \x01(\x05\x12\x39\n\x0cupdated_loca\x18\x02 \x01(\x0b\x32#.SatelliteResponse.LocationResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'satellite_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SATELLITEREQUEST']._serialized_start=20
  _globals['_SATELLITEREQUEST']._serialized_end=207
  _globals['_SATELLITEREQUEST_REQUESTTYPE']._serialized_start=148
  _globals['_SATELLITEREQUEST_REQUESTTYPE']._serialized_end=207
  _globals['_SATELLITERESPONSE']._serialized_start=210
  _globals['_SATELLITERESPONSE']._serialized_end=575
  _globals['_SATELLITERESPONSE_LOCATIONRESPONSE']._serialized_start=391
  _globals['_SATELLITERESPONSE_LOCATIONRESPONSE']._serialized_end=446
  _globals['_SATELLITERESPONSE_TIMERESPONSE']._serialized_start=448
  _globals['_SATELLITERESPONSE_TIMERESPONSE']._serialized_end=481
  _globals['_SATELLITERESPONSE_MOVERESPONSE']._serialized_start=483
  _globals['_SATELLITERESPONSE_MOVERESPONSE']._serialized_end=575
# @@protoc_insertion_point(module_scope)
